# Generated by Django 5.1.1 on 2024-09-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0002_alter_prediction_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="study",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="study",
            name="description",
        ),
        migrations.RemoveField(
            model_name="study",
            name="title",
        ),
        migrations.RemoveField(
            model_name="study",
            name="year",
        ),
    ]
