# Generated by Django 5.1.1 on 2024-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0003_remove_study_abstract_remove_study_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
