# Generated by Django 5.1.1 on 2024-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0004_alter_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
