# Generated by Django 5.1.1 on 2024-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0005_alter_label_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labelclass",
            old_name="is_multilable",
            new_name="is_multilabel",
        ),
    ]
