# Generated by Django 5.1.1 on 2024-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0006_rename_is_multilable_labelclass_is_multilabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="abstract",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="study",
            name="authors",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="study",
            name="doi",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="study",
            name="keywords",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="study",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="study",
            name="url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="study",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
