# Generated by Django 5.1.1 on 2024-09-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psynamic", "0007_study_abstract_study_authors_study_doi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
