services:
  psych:
    stdin_open: true
    build: 
      context: .
      args:
        PRODIGY_KEY: key # replace with your Prodigy key
        PRODIGY_VERSION: 1.15.3
    ports:
      - "8080:8080"
    environment:
      - PRODIGY_HOST=0.0.0.0 
      - PRODIGY_PORT=8080
    volumes:
      - ./prodigy_data:/root/.prodigy
      - ./export:/export
volumes:
  prodigy_data:
  export:
